plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rzm.socialsecurity'
    compileSdk 34

    defaultConfig {
        applicationId "com.rzm.socialsecurity"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    // 渠道配置
    flavorDimensions "channel"
    productFlavors {
        huawei {
            dimension "channel"
            // 华为渠道特有配置
            manifestPlaceholders = [CHANNEL_ID: "huawei"]
        }
        xiaomi {
            dimension "channel"
            manifestPlaceholders = [CHANNEL_ID: "xiaomi"]
        }
        oppo {
            dimension "channel"
            manifestPlaceholders = [CHANNEL_ID: "oppo"]
        }
        vivo {
            dimension "channel"
            manifestPlaceholders = [CHANNEL_ID: "vivo"]
        }
        lianxiang {
            dimension "channel"
            manifestPlaceholders = [CHANNEL_ID: "lianxiang"]
        }
    }

    buildFeatures {
        buildConfig true  // 启用 BuildConfig 生成功能
    }

    signingConfigs {
        release {
            storeFile file("/Users/zenglinggui/Documents/ad/juduo.jks")
            storePassword "juduo123"
            keyAlias "juduo"
            keyPassword "juduo123"
        }
        debug {
//            storeFile file("/Users/zenglinggui/Documents/ad/juduo.jks")
//            storePassword "juduo123"
//            keyAlias "juduo"
//            keyPassword "juduo123"
        }
    }

    buildTypes {
        debug {
            debuggable true
//            minifyEnabled true //开启混淆
//            shrinkResources false //移除无用资源
//            zipAlignEnabled false //zipalign优化
//            signingConfig signingConfigs.debug
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        release {
            minifyEnabled true //开启混淆
            shrinkResources false //移除无用资源
            zipAlignEnabled true //zipalign优化
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            buildConfigField("boolean", "LOG_DEBUG", "false")//正式版不打印日志
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    packagingOptions {
        exclude 'AndroidManifest.xml' // 忽略 .aar 文件中的 AndroidManifest.xml
    }
}

dependencies {

    implementation fileTree(include: ['*.jar', '*.aar'], dir: 'libs')

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.activity:activity:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation project(':base')
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'

    implementation 'com.blankj:utilcode:1.29.0'
    //glide
    api 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
    //SharedPreferences
    implementation "com.orhanobut:hawk:2.0.1"
    //okhttp
    implementation "com.squareup.okhttp3:okhttp:4.7.2"
    //rxjava和retrofit
    implementation 'io.reactivex.rxjava3:rxjava:3.0.4'
    implementation 'io.reactivex.rxjava3:rxandroid:3.0.2'
    implementation 'com.squareup.retrofit2:retrofit:2.8.1'
    implementation 'com.squareup.retrofit2:converter-gson:2.8.1'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.8.1'
    //添加HttpLoggingInterceptor
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'

    implementation "com.android.support:support-v4:28.0.0"

    //底部tab导航
    implementation 'me.majiajie:pager-bottom-tab-strip:2.4.0'
    //多dex
    implementation 'com.android.support:multidex:2.0.1'
    // 屏幕适配
//    implementation 'com.github.JessYanCoding:AndroidAutoSize:v1.2.1'
    // popup
    implementation "com.kongzue.dialogx:DialogX:0.0.49"
    // 选择器
    implementation 'com.github.gzu-liyujiang.AndroidPicker:Common:4.1.14'
    implementation 'com.github.gzu-liyujiang.AndroidPicker:WheelView:4.1.14'
    implementation 'com.github.gzu-liyujiang.AndroidPicker:WheelPicker:4.1.14'
    // 下载
    implementation 'com.liulishuo.filedownloader:library:1.7.7'
    // 友盟
    implementation 'com.umeng.umsdk:common:+'//必选
    implementation 'com.umeng.umsdk:asms:+'//必选
    implementation 'com.umeng.umsdk:apm:+'// U-APM产品包依赖，必选
    // eventbus
    implementation 'org.greenrobot:eventbus:3.3.1'


    implementation 'com.maven.local:Baidu_MobAds_SDK:9.3941'
    implementation 'com.maven.local:GDTSDK:4.642.1512'
    implementation 'com.maven.local:kssdk-ad:4.6.30.1'

//    implementation 'com.maven.local:mbridge_chinasame:16.6.57'
//    implementation 'com.maven.local:mbridge_dycreator:16.6.57'
//    implementation 'com.maven.local:mbridge_interstitial:16.6.57'
//    implementation 'com.maven.local:mbridge_interstitialvideo:16.6.57'
//    implementation 'com.maven.local:mbridge_mbbanner:16.6.57'
//    implementation 'com.maven.local:mbridge_mbbid:16.6.57'
//    implementation 'com.maven.local:mbridge_mbjscommon:16.6.57'
//    implementation 'com.maven.local:mbridge_mbnative:16.6.57'
//    implementation 'com.maven.local:mbridge_mbnativeadvanced:16.6.57'
//    implementation 'com.maven.local:mbridge_mbsplash:16.6.57'
//    implementation 'com.maven.local:mbridge_nativeex:16.6.57'
//    implementation 'com.maven.local:mbridge_newinterstitial:16.6.57'
//    implementation 'com.maven.local:mbridge_playercommon:16.6.57'
//    implementation 'com.maven.local:mbridge_reward:16.6.57'
//    implementation 'com.maven.local:mbridge_videocommon:16.6.57'
//    implementation 'com.maven.local:mbridge_videojs:16.6.57'
//    implementation 'com.maven.local:mediation_admob_adapter:17.2.0.71'
    implementation 'com.maven.local:mediation_baidu_adapter:9.3941.0'
    implementation 'com.maven.local:mediation_gdt_adapter:4.642.1512.0'
    implementation 'com.maven.local:mediation_ks_adapter:4.6.30.1.0'
//    implementation 'com.maven.local:mediation_mintegral_adapter:16.6.57.14'
//    implementation 'com.maven.local:mediation_sigmob_adapter:4.24.0.0'
//    implementation 'com.maven.local:mediation_unity_adapter:4.3.0.38'
    implementation 'com.maven.local:open_ad_sdk:7.1.3.2'
//    implementation 'com.maven.local:tools-release:1.0.0' // todo 上线需删除
//    implementation 'com.maven.local:unity-ads:4.3.0'
//    implementation 'com.maven.local:windAd:4.24.0'
//    implementation 'com.maven.local:windAd-common:1.8.3'
}